version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
